---
# file: playbooks/setup_sudo_user.yml

- name: "Setup sudo user and disable root login"
  hosts: webservers
  remote_user: root
  vars_files:
    - ../config/secrets.yml

  tasks:
    ## Create a new user with sudo access
    - name: create a new user
      user: >
        name={{ sudo_user }}
        password={{ sudo_user_password }}
        groups="sudo"
        shell=/bin/bash
        state=present

    ## Configure SSH
    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
      notify: restart ssh

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: restart ssh

    - name: Add id_rsa.pub from this machine
      authorized_key: user="{{ sudo_user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  handlers:
  - name: restart ssh
    sudo: yes
    service: name=ssh state=restarted
